# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main_gui.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('custom_di.json', '.'),
        ('dlt645_di.json', '.'),
        ('gdw_custom_afn.json', '.'),
        ('icons', 'icons'),
        ('enhanced_export.py', '.'),  # 增强导出模块
    ],
    hiddenimports=[
        # 数据处理依赖（Excel/CSV导出必需）
        'pandas',
        'openpyxl',
        'openpyxl.cell',
        'openpyxl.styles',
        'openpyxl.utils',
        'openpyxl.workbook',
        'openpyxl.writer.excel',
        # 项目内部模块
        'enhanced_export',
        'protocol_parser',
        'plc_rf_parser',
        'hdlc_parser',
        'dlt645_parser',
        'gdw10376_parser',
        'dl_t698_45_parser',
        'csg_new_gen_parser',
        'gw_new_gen_parser',
        'gw_new_gen_cmd_payloads',
        'obis_lookup',
        'command_lookup',
        'dlt645_di_lookup',
        'gdw_afn_lookup',
        'frame_gen_widget',
        'archive_widget',
        'topology_widget',
        'preset_buttons',
        'test_plan_widget',
        'diff_widget',
        'serial_worker',
        'gui_utils',
        'frame_diff_engine',
        'lua_script_engine',
        # 可选依赖
        'crcmod',
        'serial',
        'serial.tools',
        'serial.tools.list_ports',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PyQt5',
        'PyQt6',
        'matplotlib',
        'scipy',
        'PIL',
        'tkinter',
        '_tkinter',
        'IPython',
        'notebook',
        'jupyter',
        'pytest',
        'unittest',
        # 注意：pandas/numpy/openpyxl 不能排除，否则 Excel/CSV 导出功能会失效
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='协议解析工具',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='app_icon.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='协议解析工具',
)
